<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head head-adminhtml-manufacturer">Homebook.pl XML</h3></td>
            <td class="form-buttons"><a id="homebook_id" title="homebook.xml" target="_blank"  href="/homebook.xml" style=""><span><span><span>download homebook.xml</span></span></span></a></td>
        </tr>
        </tbody></table>
</div>

<div class="moz-signature">
    <div class="moz-signature">
        <div class="moz-signature">
            <div class="moz-signature">
                <div class="moz-signature">
                    <div class="moz-signature">
                        <div class="moz-signature">
                            <meta http-equiv="content-type" content="text/html;
                    charset=utf-8">
                            <div class="moz-signature">
                                <div class="moz-signature">
                                    <div class="moz-signature">
                                        <div class="moz-signature">
                                            <meta http-equiv="content-type"
                                                  content="text/html; charset=utf-8">
                                            <title>Sylwester Kowal</title>
                                            <br>
                                            <div class="moz-signature">
                                                <div class="moz-signature">
                                                    <div class="moz-signature">
                                                        <div class="moz-signature">
                                                            <div class="moz-signature">
                                                                <div class="moz-signature">
                                                                    <div class="moz-signature">
                                                                        <div class="moz-signature">
                                                                            <div class="moz-signature">
                                                                                <div class="moz-signature">
                                                                                    <div class="moz-signature">
                                                                                        <div
                                                                                            class="moz-signature">
                                                                                            <div
                                                                                                class="moz-signature">
                                                                                                <div
                                                                                                    class="moz-signature">
                                                                                                    <div
                                                                                                        class="moz-signature">
                                                                                                        <font size="-1">
                                                                                                        </font>
                                                                                                        <div><font
                                                                                                                color="#666666"
                                                                                                                size="-1"> <font
                                                                                                                    color="#999999"><a href="http://sylwesterkowal.com"><img alt="sylwester"
                                                                                                                                                                             title="sylwester" moz-do-not-send="false"
                                                                                                                                                                             src="/skin/adminhtml/default/wm21w/sylwester_kowal.png"
                                                                                                                                                                             height="43"
                                                                                                                                                                             align="middle"
                                                                                                                                                                             border="0"
                                                                                                                                                                             width="43"></a>&nbsp;













                                                                                                                    <font
                                                                                                                        size="-2"><font
                                                                                                                            color="#444"><br>
                                                                                                                            Sylwester
                                                                                                                            Kowal&nbsp; <br>
                                                                                                                            <br>
                                                                                                                        </font></font></font></font><font
                                                                                                                color="#666666" size="-1"><font size="-2"><font color="#000000"><font
                                                                                                                            color="#666666"
                                                                                                                            size="-1"><font
                                                                                                                                size="-2">Telefon:
                                                                                                                            </font></font>+48
                                                                                                                        608 012 047</font>
                                                                                                                    &nbsp; |
                                                                                                                    &nbsp; Skype:
                                                                                                                    <font
                                                                                                                        color="#000000">kowal.sylwester</font>&nbsp;















                                                                                                                    &nbsp; |&nbsp;
                                                                                                                    &nbsp; GG: <font
                                                                                                                        color="#000000">52704063<br>
                                                                                                                    </font></font></font><font
                                                                                                                color="#666666" size="-1"><font size="-2"><font color="#000000"><font
                                                                                                                            color="#666666"
                                                                                                                            size="-1"><font
                                                                                                                                size="-2">Portfolio:
                                                                                                                            </font></font></font></font></font><font
                                                                                                                color="#666666" size="-1"><font color="#999999"><font size="-2"><a
                                                                                                                            href="http://sylwesterkowal.com">sylwesterkowal.com</a><font
                                                                                                                            color="#444"><br>
                                                                                                                        </font></font></font></font><br>
                                                                                                            <p> <font
                                                                                                                    color="#999999"
                                                                                                                    size="1"> </font><font
                                                                                                                    color="#444444" size="1"><font color="#444444" size="1"><a
                                                                                                                            href="http://21w.pl"><img
                                                                                                                                alt="21w.pl"
                                                                                                                                title="21w.pl"
                                                                                                                                src="/skin/adminhtml/default/wm21w/wdrozenia-magento.jpg"
                                                                                                                                height="43"
                                                                                                                                align="middle"
                                                                                                                                border="0"
                                                                                                                                width="43"></a></font><font
                                                                                                                        color="#444444" size="1">&nbsp; &nbsp; </font></font><font size="1"><a
                                                                                                                        href="http://21w.pl"><font size="1">21w.pl</font></a></font><font
                                                                                                                    color="#444444"
                                                                                                                    size="1"><font
                                                                                                                        color="#444444" size="1"> - Wdrożenia sklepów Magento</font><font
                                                                                                                        color="#444444"
                                                                                                                        size="1"><br>
                                                                                                                    </font><a
                                                                                                                        href="http://21erp.pl"><img
                                                                                                                            alt="Wdrożenie
                                                          ERP"
                                                                                                                            title="Wdrożenie
                                                          ERP"
                                                                                                                            src="/skin/adminhtml/default/wm21w/wdrozenie-erp.jpg"
                                                                                                                            height="43"
                                                                                                                            align="middle"
                                                                                                                            border="0"
                                                                                                                            width="43"></a>&nbsp;&nbsp;&nbsp;


                                                                                                                    <a
                                                                                                                        href="http://21erp.pl">21erp.pl</a>
                                                                                                                    - Wdrożenia
                                                                                                                    aplikacji ERP</font><br>
                                                                                                                <font
                                                                                                                    color="#444444"><font
                                                                                                                        size="1"><a
                                                                                                                            href="http://21crm.pl"><img
                                                                                                                                alt="Wdrożenia
                                                          CRM"
                                                                                                                                title="Wdrożenia
                                                          CRM"
                                                                                                                                src="/skin/adminhtml/default/wm21w/wdrozenie-crm.jpg"
                                                                                                                                height="43"
                                                                                                                                align="middle"
                                                                                                                                border="0"
                                                                                                                                width="43"></a>&nbsp;&nbsp;&nbsp;

                                                                                                                        <a
                                                                                                                            href="http://21crm.pl">21crm.pl</a>
                                                                                                                        - Wdrożenia
                                                                                                                        aplikacji CRM</font></font><br>
                                                                                                                <font
                                                                                                                    color="#444444"
                                                                                                                    size="1"><a
                                                                                                                        href="http://21crm.pl"><font
                                                                                                                            color="#444444"> </font></a></font></p>
                                                                                                            <p><font
                                                                                                                    size="1"><font
                                                                                                                        size="-1"><br>
                                                                                                                        21w.pl
                                                                                                                        Sylwester
                                                                                                                        Kowal</font></font><font
                                                                                                                    size="1"><br>
                                                                                                                    38 - 100
                                                                                                                    Strzyżów</font><font
                                                                                                                    size="1">,
                                                                                                                    Dobrzechów 509</font><font
                                                                                                                    size="1"><br>
                                                                                                                    NIP:
                                                                                                                    7951418889<br>
                                                                                                                    <font
                                                                                                                        size="-2"><br>
                                                                                                                    </font></font><font
                                                                                                                    color="#666666" size="-1"><br>
                                                                                                                </font></p>
                                                                                                            <p><br>
                                                                                                            </p>
                                                                                                            <p><font
                                                                                                                    size="-1"> </font><br>
                                                                                                            </p>
                                                                                                        </div>
                                                                                                    </div>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

